apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: NodePort
  selector:
    app: redis
  clusterIP: 100.100.100.100
  ports:
  - name: "1"
    port: 6379
    protocol: TCP
    targetPort: 6379
    nodePort: 31009