apiVersion: v1
kind: Pod
metadata:
  name: springboot
  labels:
     app: springboot  
spec:
     containers:
        - name: springboot
          image: 1964262317/springboot-docker:v1.0
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080
     restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  type: NodePort
  sessionAffinity: ClientIP
  selector:
    app: springboot
  ports:
    - port: 8080
      nodePort: 30080